import { ChevronLeft, ChevronRight, Search } from "lucide-react";

const statusClasses = { Committed: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", Pending: "bg-amber-500/10 text-amber-400 border-amber-500/20", Replicated: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20" };
function LogEntriesTable({ logs }) {
  return <div className="glass-card rounded-2xl overflow-hidden shadow-[0_8px_32px_rgba(0,0,0,0.3)]">
    <div className="px-5 py-4 border-b border-slate-900 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-slate-200">Log Entries</h2><p className="text-[10px] text-slate-500 mt-1">Recent replicated state-machine commands</p></div><label className="flex items-center gap-2 bg-slate-950/70 border border-slate-800 rounded-xl px-3 py-2 text-slate-500 focus-within:border-indigo-500/40 transition-colors"><Search size={13} /><input aria-label="Search log entries" className="w-40 bg-transparent outline-none text-xs text-slate-300 placeholder:text-slate-600" placeholder="Search log entries..." /></label></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="sticky top-0 z-10 bg-[#0d0f1b] text-[9px] uppercase tracking-wider text-slate-500"><tr>{["Index", "Term", "Command", "Key", "Value", "Status"].map(h => <th key={h} className="px-5 py-3.5 font-extrabold border-b border-slate-900">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-900/70">{logs.map(log => <tr key={log.index} className="hover:bg-white/[0.025] transition-colors"><td className="px-5 py-3.5 text-xs font-bold text-indigo-400 font-mono">{log.index}</td><td className="px-5 py-3.5 text-xs text-slate-400 font-mono">{log.term}</td><td className="px-5 py-3.5"><span className="text-[10px] font-extrabold text-slate-300 bg-slate-950 border border-slate-800 rounded-md px-2 py-1">{log.command}</span></td><td className="px-5 py-3.5 text-xs text-slate-300 font-mono">{log.key}</td><td className="px-5 py-3.5 text-xs text-slate-500 font-mono max-w-44 truncate">{log.value}</td><td className="px-5 py-3.5"><span className={`text-[9px] font-extrabold uppercase tracking-wider px-2.5 py-1 rounded-full border ${statusClasses[log.status]}`}>{log.status}</span></td></tr>)}</tbody></table></div>
    <div className="px-5 py-3 border-t border-slate-900 flex items-center justify-between text-[10px] text-slate-500"><span>Showing 1–{logs.length} of {logs.length} entries</span><div className="flex gap-1"><button aria-label="Previous page" className="p-1.5 rounded-lg border border-slate-800 text-slate-600"><ChevronLeft size={13} /></button><button aria-label="Next page" className="p-1.5 rounded-lg border border-slate-800 text-slate-500 hover:text-slate-300"><ChevronRight size={13} /></button></div></div>
  </div>;
}
export default LogEntriesTable;
